### ISSUE TITLE
Reconsider `:pathom/context` implementation

### ISSUE THREAD

**Issue by thenonameguy** [wilkerlucio/pathom#140]
While you can provide more than key/value pair for the initial context of parsing with the `:pathom/context` parameter, wouldn't it be syntactically nicer to support it with an unused variant of the EQL join spec? I.e.:
```clojure
[{{:init-context/a 42 :init-context/b "foo"} [:want/this]}]
```
vs.
```clojure
[{([:init-context/a 42] {:pathom/context {:init-context/b "foo"}}) [:want/this]}]
```
My general sentiment is that the current ident-focus of EQL works well for single keyed entities like user/account, etc. But fails to cleanly model compound key entity retrieval (without unnecessary nesting), unless you want to model the compound key as a single attribute.

**Comment by wilkerlucio** [comment]
Hello, thanks for the posting, I like to clarify the intentions around those. First, yes, the ident is meant to be an identifier, the reason why context and ident are separated things is on purpose, because one is about the "identification" of something, while the other is about giving extra information (context), this is way they are handled this way.

About compound keys, I like to remember that the ident value can be anything, so if you want to use a compound key, make the ident value something compound, like:

```clojure
[{[:compunded-identity {:init-context/a 42 :init-context/b "foo"}] [:want/this]}]
```

This way you can have a clear separation about what is identity, and what is just extra stuff you wanna send.

Makes sense?

**Comment by wilkerlucio** [comment]
Two more things about this:

1. If you write some special compound key, you can expand that into the separated values by using more resolvers, example, the query `[{[:thing-compound ["foo" "bar"]] [:thing/id]}]`

Then you could expand into the values with:

```clojure
(pc/defresolver expand-thing-compound [env {:keys [thing-compound]}]
  {::pc/input  #{:thing-compound}
   ::pc/output [:thing/piece-a :thing/other-piece]}
  {:thing/piece-a (first thing-compound)
   :thing/other-piece (second thing-compound)})
```

Also, you could write a resolver in the other direction, to get the separated pieces and make the vector, this way you have official compound keys.

That said, I recommend you try to avoid them, IME compound keys tend to become sources of complexity of time, if you have the possibility to give real unique ids to everything, you should stick to that, because it's simpler and will make your life easier.

**Comment by thenonameguy** [comment]
Thanks for the elaborate answer! Yes, this is the way we have been doing for the time being. Having confirmed that this is the way to go sounds better. One another use-case for `:pathom/context` is the what-if scenario as outlined in the docs. 
Today you can do this with something like:
```clojure
[{(:>/given {:pathom/context {:user/first-name "John" :user/last-name "Doe"}})
 [:user/full-name]}]
```
My issue with this is that I had to create a placeholder ident name just for the sake of the ident.
I think my overloading of the key in the join just with the value in `:pathom/context` would make it clearer on the response side.
```clojure
(let [ctx {:user/first-name "John" :user/last-name "Doe"}
      resp (<!! (parser {} [{ctx [:user/full-name]}]))
    (str "Hello " (get-in resp [ctx :user/full-name]))))
```
Would you be interested in an optionally includeable parser plugin for this? Of courser the EQL spec should support this extension for spec checking but I don't think it's entirely unreasonable for this usecase, and removes the need for creating compound key attributes (which don't really exists).

**Comment by wilkerlucio** [comment]
Can you clarify that a bit more, I'm not getting it. If you want to set the context from "outside the query" you can do in a simpler way, like:

```clojure
(let [ctx {:user/first-name "John" :user/last-name "Doe"}
      resp (<!! (parser {::p/entity (atom ctx)} [:user/full-name]))
    (str "Hello " (get resp [:user/full-name]))))
```

Does that work for your case?

**Comment by wilkerlucio** [comment]
Also, I believe placeholders don't support `:pathom/context`, that's a feature from the `ident-reader` and `open-ident-reader`, technically that could be added to the placeholder reader, but I'm afraid this could lead to some strange unexpected processing results.

**Comment by thenonameguy** [comment]
> Can you clarify that a bit more, I'm not getting it. If you want to set the context from "outside the query" you can do in a simpler way, like:
> 
> ```clojure
> (let [ctx {:user/first-name "John" :user/last-name "Doe"}
>       resp (<!! (parser {::p/entity (atom ctx)} [:user/full-name]))
>     (str "Hello " (get resp [:user/full-name]))))
> ```
> 
> Does that work for your case?

For the regular Pathom use-case where you only pass in the query from an HTTP request for instance it does not (since you have to pass in `{::p/entity (atom ctx)}` as env based on some condition in the request itself (not the query). My point would be to set a base context/entity in a join inside the query to combine attributes that weren't considered before via a nicer syntax.

**Comment by wilkerlucio** [comment]
I like to be very strict about changing the EQL syntax, this use case I don't find convincing enough like we said you can use composite keys, or `:pathom/context`, or a combination of them, you can also create your own readers to elaborate more in the params side, and there is also even another layer you can use that is the query meta, you can attach data there and use in the process as well. Given all these options I don't see the need for a new one at this time. If you have new points feel free to re-open.
