### ISSUE TITLE
Idents with keys, and no values, throw a WARN, even though they work

### ISSUE THREAD

**Issue by kendagriff** [wilkerlucio/pathom#185]
Per the documentation, idents without values appear to work:

```clojure
;; query
[:person/name]

;; possible result
{:person/name "Samantha"}
```

https://blog.wsscode.com/pathom/#_the_basics

In my own resolvers, however, something like this:

```clojure
(def get-user
  {::pc/sym `get-user
   ::pc/input #{:session/id}
   ::pc/output [:user/id]
   ::pc/resolve (fn [_ _]
                  ; (let id ...)
                  {:user/id id})})
```
With a query like this:

```clojure
[{[:session/id] [:user/id]}]
```

Yields the correct value, but prints a warning alongside it:

```
WARN: trying to read key [:session/id] which is not available in the index.
```

Passing any value in the ident will sidestep the warning:

```clojure
[{[:session/id nil] [:user/id]}]
```

This seems like a bug, do you mind taking a look?

**Comment by wilkerlucio** [comment]
Hello, the issue is that `[{[:session/id] [:user/id]}]` is not an ident request. The warning is telling you not about the key `:session/id`, but the key `[:session/id]`.

A valid EQL ident is always a vector of exact two elements; `[:session/id]` in this case means that specific key, in the same way, that `[:session/id 123 421 421]` is a valid key on itself, but also not an ident.

Makes sense?

**Comment by kendagriff** [comment]
Got it! Appears I was looking for a resolver with an input of `#{}` and an output of `[:session/id]`, and a second resolver that receives `[:session/id]` and outputs `[:user/id]`.
