### ISSUE TITLE
Allow using vars instead of raw keywords in defresolver and defmutation

### ISSUE THREAD

**Issue by avocade** [wilkerlucio/pathom#189]
We're gradually moving towards using the same `*-options` pattern that [fulcro RAD uses](https://github.com/fulcrologic/fulcro-rad/blob/develop/src/main/com/fulcrologic/rad/attributes_options.cljc), and wrap all keywords in vars (for better IDE checking). So it would be great if we could use these vars also in the config maps for pathom resolvers and mutations (and in non-RAD fulcro `defsc` of course, but that's for another issue).

```clojure
(defresolver kg->pounds
  [_env {kg weight/kg}]
  {::pc/input  #{weight/kg}                                
   ::pc/output [weight/lbs]}
  {weight/lbs (* kg 2.204623)})
  
;; Where weight/kg => (def kg ::kg)
```

**Comment by wilkerlucio** [comment]
This makes really hard for Pathom to infer inputs and outputs automatically with this. For now, you can already do it if you use `resolver` and `mutation` instead of `defresolver`. I'll have to think about this, because I'm not sure if I want to encourage this kind of pattern, especially when https://clojure.atlassian.net/browse/CLJ-2123 is close to getting ready. If you think about that, symbols to keywords are worst for static analysis than plain keywords, because of the indirection, you know have to always look for both the symbol and the keyword, because you never know if somebody just used the keyword directly.

If you want something just quick now, I suggest you write your own macro for `defresolver`, if you don't use the inference part (which can't work with symbols like this) its a trivial macro to write, just to get `::pc/sym` and the var name the same.

**Comment by avocade** [comment]
Interesting, I didn't know about the upcoming "lighter-weight namespace aliasing" feature. Not sure I understand what are the benefits of that in this particular case, but want to learn :)

I think RAD does this "resolve var to keyword" step in all places where it can expect either a raw keyword or a variable, eg in `defattr`. Would be interesting to know from @awkay if the thinks it's a pattern he'll stick with or move away from at this point.

**Comment by awkay** [comment]
Doing the resolution in macros works fine as long as you require that the options namespaces (which you control) are in CLJC, since that way the macro can always resolve them. I allow other vars as keys in the options maps (e.g. someone could define something only in CLJS), but if I didn't write it, then I don't care if it resolves, because my macro can't possibly have known about it, so it cannot possibly care. So, in RAD at least, this pattern is something I value and will continue, because you would rather have the docstring there, where the options abound, and the macro only cares about the ones it is written to use, which I control.  

In Pathom it's a harder problem since these magic maps and such has to resolve *all* the possible keywords. It adds a constraint that such a keyword *must* be def'd in a CLJ(C) file, or the macro is intractably hard to write.

**Comment by avocade** [comment]
Thanks for the clarification. Having vars instead of raw keys is a great help, even if they aren't (of course) additionally checked against the "allowed" options, eg in `defsc-form`.

**Comment by wilkerlucio** [comment]
Nothing to do here, closing it for now.
