### ISSUE TITLE
Revisiting the same node multiple times in the same pull, but with different queries

### ISSUE THREAD

**Issue by slurpbarf** [wilkerlucio/pathom#212]
Hey!

Recently been running into some issues with deep pull queries through Pathom, where the same node is being visited multiple times.

This was the smallest possible example I could come up with:

```clojure

;; I have a graph as such ...

[{:id 1 
  :a 1 
  :b [2]} 
 {:id 2 
  :c "Hello world"}]

;; ... with a resolver that matches all fields on the node.

;; I run the following pull-query:

(p.eql/process env
  {:id 1}
  [:id 
   {:a [:id 
         {:b [:id :c]}]}])

;; ... and get this:
;; =>
;; {:id 1
;;  :a  {:id 1}}

;; Expectation:
;; {:id 1
;;  :a  {:id 1
;;       :b  [:id 2 :c "Hello world"]}}

```

Obviously this is a ridiculous example, but we have some real queries that function in a similar way (e.g. walk from `entity-1` -> `entity-1-kind` -> `all-entities-of-entity-1-kind` -> Perform some pull query).

If you have any clues at to what in Pathom causes this to occur or any recommendations, that would be great!

As a work-around we have collected the union of all fields we need in the earliest position the entity can be pulled (in the above example, at the root of the query-vector), and that works because we are flattening the result before sending it off to the client. But it is a bit of a mental burden to keep track of :)

Thanks!

**Comment by slurpbarf** [comment]
We are modelling a graph so it is quite likely that we will (either on purpose or by chance) be visiting the same node multiple times for complex queries. In most cases with different queries each time the node is being resolved.

**Comment by eneroth** [comment]
Hi Wilker!

So also, we're sourcing the expectations from `[::pcn/node ::pcn/expects]`. Since we're dealing with data that is graph-like in nature, like @slurpbarf points out, the hope from our side would be that the node is that either:

a) The node is visited as many times as it is asked for in the query, and that we get the approriate `expects` handed to us each time, or that
b) The node is visited once, and we can get the sum of all expectations, after which Pathom will take the total result, split it, and place the parts of it in the results such that it corresponds to the query.

Don't exactly see how b) could happen, since it's only by walking down the tree that Pathom could discover that the node is showing up again.

**Comment by wilkerlucio** [comment]
Hello folks, I'm trying to understand the case here. I think would be useful to see the graphs so we can understand what the planner is doing, and possibly find some opportunities for improvement.

Pathom planner works in two phases, first it expands the needs for all the query requirements, later it optimizes the plan to reduce redundancies. So I'm guessing some redundancy might be missing, making you have multiple nodes for the same resolver, with different `::pco/expects` (because they were born to fulfill different requirements).

To get the plan, you can extract it from the `meta` in the result object, you will find it there, if you use Pathom Viz you can even render that graph. Please let me know if you have any difficulties to get that.

One other thing, can we please re-open this issue on the Pathom 3 repo? From your code I see you are using that, but this repo here is for Pathom 2 :)

Cheers, and sorry the delay for the answer here.

**Comment by slurpbarf** [comment]
No worries, appreciate you getting back to us :) I don't have the spare bandwidth for this right now, but will get back to you in a few days, after having checked out the planner. Closing this in the meantime and opening a new issue in the Pathom3 repo then.
